language: python
dist: xenial
python:
  - "2.7"
env: explorer
sudo: required

cache:
  pip: true
  directories:
    - $HOME/buildout-cache

before_install:
  - sudo -H pip install selenium
  - sudo -H pip install --upgrade pip
  - sudo -H pip install requests
  - sudo -H apt-get -qq install xvfb python-virtualenv chromium-browser
  - wget http://chromedriver.storage.googleapis.com/index.html?path=2.46/chromedriver_linux64.zip
  - sudo -H unzip chromedriver_linux64.zip 
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  - export CHROME_HOME=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - sudo -H apt-get install lftp
  - chmod +x bdd/upload2Ftp.sh
#before_script:

script:    
  - python PalletoneExplorer/more/viewSettings/viewSettings.py
env:
  - BROWSER="Chrome"
  #- BROWSER="Firefox"

        
addons:
  apt:
    update: true