language: python
dist: xenial
sudo: required
addons:
  chrome: stable
  apt:
    update: true
python:
  - "2.7"
env:
  global:
    #- BASE_DIR=/home/travis/palletone/go-palletone/explorer_test/PalletoneExplorer/
    - IS_UPLOAD=true
    - PIP_PATH=/usr/local/lib/python2.7/site-packages/

before_install:
  - export PYTHONPATH=/home/travis/build/palletone/explorer_test/PalletoneExplorer:/usr/bin:/usr/lib/python2.7/:/usr/local/lib/python2.7/
  - ls -l /usr/lib/python2.7/dist-packages
  - ls -l /usr/local/lib/python2.7/dist-packages
  - sudo -H pip install --upgrade pip
  - sudo -H pip install --target=${PIP_PATH} selenium
  #- python -m pip install -U selenium
  - sudo -H pip install --target=${PIP_PATH} unittest2
  - sudo -H pip install --target=${PIP_PATH} requests
  - sudo -H apt-get -qq install xvfb python-virtualenv 
  #chromium-browser
  - wget http://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip
  - sudo -H apt-get install unzip
  - sudo -H unzip chromedriver_linux64.zip 
  - pwd
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  #- export CHROME_HOME=chromium-browser
  - Xvfb -ac :7 -screen 0 1366x768x8 &
  #- export DISPLAY=:7
  - sleep 3

install:
  - sudo -H apt-get install lftp
  - chmod +x PalletoneExplorer/upload2Ftp.sh

script:
  - echo $PATH
  - echo $PYTHONPATH
  - ls -l /usr/local/lib/python2.7/dist-packages
  - python PalletoneExplorer/more/viewSettings/viewSettings.py
#env:
  #- BROWSER="Chrome"
  #- BROWSER="Firefox"

after_script:
  - |
    if [ $IS_UPLOAD == 'true' ]; then
      ./bdd/upload2Ftp.sh ${FTP_PWD} ${TRAVIS_BRANCH};